 <?php
      //数据
	  $result_1=array(
		'0'=>array(
				'city'=>array(
						'id'=>'1',
						'name'=>'三亚'
							),
				'spots'=>array(
						'id'=>'1',
						'name'=>'南山寺'
							),
				'count'=>'133'
			),
		'1'=>array(
				'city'=>array(
						'id'=>'2',
						'name'=>'平谷区'
							),
				'spots'=>array(
						'id'=>'2',
						'name'=>'渔阳国际滑雪'
							),
				'count'=>'129'
			),
		'2'=>array(
				'city'=>array(
						'id'=>'3',
						'name'=>'保定市'
							),
				'spots'=>array(
						'id'=>'3',
						'name'=>'清西陵'
							),
				'count'=>'110'
			),
		'3'=>array(
				'city'=>array(
						'id'=>'4',
						'name'=>'泉州'
							),
				'spots'=>array(
						'id'=>'4',
						'name'=>'苏夫人姑庙'
							),
				'count'=>'110'
			),
		'4'=>array(
				'city'=>array(
						'id'=>'5',
						'name'=>'南昌市'
							),
				'spots'=>array(
						'id'=>'5',
						'name'=>'鄱阳湖'
							),
				'count'=>'82'
			),
		'5'=>array(
				'city'=>array(
						'id'=>'6',
						'name'=>'厦门'
							),
				'spots'=>array(
						'id'=>'6',
						'name'=>'陈嘉庚先生故'
							),
				'count'=>'80'
			),
		'6'=>array(
				'city'=>array(
						'id'=>'7',
						'name'=>'平谷区'
							),
				'spots'=>array(
						'id'=>'7',
						'name'=>'平谷大桃采摘'
							),
				'count'=>'71'
			),
		'7'=>array(
				'city'=>array(
						'id'=>'8',
						'name'=>'西安'
							),
				'spots'=>array(
						'id'=>'8',
						'name'=>'华清池'
							),
				'count'=>'70'
			),
		'8'=>array(
				'city'=>array(
						'id'=>'9',
						'name'=>'泉州'
							),
				'spots'=>array(
						'id'=>'9',
						'name'=>'水上乐园'
							),
				'count'=>'64'
			),
		'9'=>array(
				'city'=>array(
						'id'=>'10',
						'name'=>'昌平区'
							),
				'spots'=>array(
						'id'=>'10',
						'name'=>'温都水城'
							),
				'count'=>'59'
			),
		'10'=>array(
				'city'=>array(
						'id'=>'11',
						'name'=>'泉州'
							),
				'spots'=>array(
						'id'=>'11',
						'name'=>'屈斗宫古窑址'
							),
				'count'=>'52'
			),
		'11'=>array(
				'city'=>array(
						'id'=>'12',
						'name'=>'怀柔区'
							),
				'spots'=>array(
						'id'=>'12',
						'name'=>'雁栖湖拓展培'
							),
				'count'=>'51'
			),
		'12'=>array(
				'city'=>array(
						'id'=>'13',
						'name'=>'石家庄'
							),
				'spots'=>array(
						'id'=>'13',
						'name'=>'苍岩山风景区'
							),
				'count'=>'49'
			)
	  );

	  $result_2=array(
		'0'=>array(
				'id'=>'1',
				'namelong'=>'【3月】韩国一地经典全景5日超值烂漫之旅（特别推荐）',
				'nameshort'=>'【3月】韩国一地经典..',
				'count'=>'73'
			),
		'1'=>array(
				'id'=>'2',
				'namelong'=>'日本 韩国经典休闲八日游 大阪 京都 箱根 横滨 东京 首尔',
				'nameshort'=>'日本 韩国经典休闲八..',
				'count'=>'42'
			),
		'2'=>array(
				'id'=>'3',
				'namelong'=>'南京、无锡、苏州、杭州、上海+中国第一水乡周庄、木渎 双水乡双卧七日',
				'nameshort'=>'南京、无锡、苏州、..',
				'count'=>'35'
			),
		'3'=>array(
				'id'=>'4',
				'namelong'=>'南京、无锡、苏州、杭州、上海+中国第一水乡周庄、木渎 双水乡双卧七日/卧飞六日',
				'nameshort'=>'南京、无锡、苏州、..',
				'count'=>'28'
			),
		'4'=>array(
				'id'=>'5',
				'namelong'=>'九江、庐山、三叠泉双卧四日游',
				'nameshort'=>'九江、庐山、三叠泉..',
				'count'=>'27'
			),
		'5'=>array(
				'id'=>'6',
				'namelong'=>'青岛、烟台、威海、蓬莱一卧一坐五日游',
				'nameshort'=>'青岛、烟台、威海、..',
				'count'=>'27'
			),
		'6'=>array(
				'id'=>'7',
				'namelong'=>'日本 韩国全景休闲十日游 大阪 京都 箱根 横滨 东京 济州 首尔',
				'nameshort'=>'日本 韩国全景休闲十..',
				'count'=>'26'
			),
		'7'=>array(
				'id'=>'8',
				'namelong'=>'北京春季踏青采摘',
				'nameshort'=>'北京春季踏青采摘',
				'count'=>'23'
			),
		'8'=>array(
				'id'=>'9',
				'namelong'=>'青岛、烟台、威海、蓬莱双卧六日游',
				'nameshort'=>'青岛、烟台、威海、..',
				'count'=>'23'
			),
		'9'=>array(
				'id'=>'10',
				'namelong'=>'承德避暑山庄 普宁寺 小布达拉宫棒槌山火车双座三日游',
				'nameshort'=>'承德避暑山庄 普宁寺..',
				'count'=>'23'
			),
		'10'=>array(
				'id'=>'11',
				'namelong'=>'青岛、崂山双卧四日游',
				'nameshort'=>'青岛、崂山双卧四日..',
				'count'=>'22'
			),
		'11'=>array(
				'id'=>'12',
				'namelong'=>'济南、泰山、曲阜双卧五日',
				'nameshort'=>'济南、泰山、曲阜双..',
				'count'=>'22'
			),
		'12'=>array(
				'id'=>'13',
				'namelong'=>'【春游植树】青龙峡踏青/植树一日游',
				'nameshort'=>'【春游植树】青龙峡..',
				'count'=>'22'
			),
		);
	//根据指定id输出html
	  if(isset($_GET['id'])){
		  switch((int)$_GET['id']) {
		  case 1: $resonseText = '<table width="217" cellspacing="0"	cellpadding="0"><tr><th>名次</th><th>景区</th><th>景点</th><th>排名</th></tr>';
					foreach($result_1 as $key => $value)
						$resonseText.= '<tr><td><img height="13" width="13" src="http://www.2008ly.com/images/index_p'.($key+1).'.gif"/></td><td><a href="getCity.php?id='.$value['city']['id'].'">'.$value['city']['name'].'</a></td><td><a href="getSpots.php?id='.$value['spots']['id'].'">'.$value['spots']['name'].'</a></td><td><span>'.$value['count'].'</span></td></tr>';
					$resonseText .= '</table>';
					echo $resonseText;break;
		  case 2:$resonseText = '<table width="217" cellspacing="0"	cellpadding="0"><tr><th>名次</th><th>线路</th><th>排名</th></tr>';
					foreach($result_2 as $key => $value)
						$resonseText.='<tr><td><img height="13" width="13" src="http://www.2008ly.com/images/index_p'.($key+1).'.gif"/></td><td><a href="getLine.php?id='.$value['id'].'" title="'.$value['namelong'].'">'.$value['nameshort'].'</a></td><td><span>'.$value['count'].'</span></td></tr>';
					$resonseText.='</table>';
					echo $resonseText;break;
		  }
	  }
  ?>